language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
script:
  - npm run lint
  - npm run test
after_success:
  - set -e
  - if [[ $TRAVIS_NODE_VERSION = 9 && "$TRAVIS_BRANCH" = "master" ]]; then bash ./release.sh; fi
